const UNPROCESSABLE_ENTITY = 422;
const HTTP_OK_NO_CONTENT = 202;
const HTTP_OK_WITH_CONTENT = 200;
const INTERNAL_ERROR = 500;
const RESOURCE_DOES_NOT_FIND = 500;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const CONFLICT = 409;
const TOKEN_TYPE = "Bearer";

module.exports = {
    CONFLICT: CONFLICT,
    TOKEN_TYPE: TOKEN_TYPE,
    UNAUTHORIZED: UNAUTHORIZED,
    FORBIDDEN: FORBIDDEN,
    UNPROCESSABLE_ENTITY: UNPROCESSABLE_ENTITY,
    HTTP_OK_NO_CONTENT: HTTP_OK_NO_CONTENT,
    HTTP_OK_WITH_CONTENT:HTTP_OK_WITH_CONTENT,
    INTERNAL_ERROR : INTERNAL_ERROR,
    RESOURCE_DOES_NOT_FIND:RESOURCE_DOES_NOT_FIND
};