service: aws-nodejs-todo
plugins:
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-aws-alias
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: test
  region: eu-central-1
  stackName: todo-bartosz-golebiowski-stack
  apiName: todo-bartosz-golebiowski-api
  deploymentBucket:
    name: todo-bartosz-golebiowski-bucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        "*"
      Resource:
        Fn::GetAtt:
          - todoTable
          - Arn

  environment:
    TODO_TABLE: 'todoTable'

custom:
  dynamodb:
    stages:
      - test
  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Serverless, nodejs todo app
    models:
      - name: createTodo
        contentType: "application/json"
        schema:
          type: object
          properties:
            name:
              type: string
          required:
            - name

      - name: updateAndDeleteTodo
        contentType: "application/json"
        schema:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
          required:
            - todo_id
            - name
      - name: getSingleTodo
        contentType: "application/json"
        schema:
          type: object
          properties:
            id:
              type: string
          required:
            - todo_id


functions:
  getAllTodo:
    handler: src/todo/todoController.getAllTodo
    name: getAllTodo
    events:
    - http:
        documentation:
          summary: "Gets all todo"
          description: "Gets all todo"
        path: todo
        method: get
  createTodo:
    handler: src/todo/todoController.createTodo
    name: createTodo
    events:
      - http:
          documentation:
            summary: "Create new todo"
            description: "Creates new todo"
            requestModels:
              "application/json": createTodo
          path: todo/create
          method: post
          reqValidatorName: onlyBody
  updateTodo:
    handler: src/todo/todoController.updateTodo
    name: updateTodo
    events:
      - http:
          documentation:
            summary: "Updates existing todo"
            description: "Updates existing todo"
            requestModels:
              "application/json": updateAndDeleteTodo
          path: todo/update
          method: patch
          reqValidatorName: onlyBody
  deleteTodo:
    handler: src/todo/todoController.deleteTodo
    name: deleteTodo
    events:
      - http:
          documentation:
            summary: "Deletes todo"
            description: "Deletes todo"
            requestModels:
              "application/json": updateAndDeleteTodo
          path: todo/delete
          method: delete
          reqValidatorName: onlyBody
  getSingleTodo:
    handler: src/todo/todoController.getSingleTodo
    name: getSingleTodo
    events:
      - http:
          documentation:
            summary: "Gets single todo"
            description: "Gets single todo"
            requestModels:
              "application/json": getSingleTodo
          path: todo/{todo_id}
          method: get
          reqValidatorName: onlyBody
resources:
  Resources:
    todoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODO_TABLE}
        AttributeDefinitions:
          - AttributeName: todo_id
            AttributeType: S
        KeySchema:
          - AttributeName: todo_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    onlyBody:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'only-body'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: true
