const UNPROCESSABLE_ENTITY = 422;
const HTTP_OK = 200;
const INTERNAL_ERROR = 500;

module.exports = {
    UNPROCESSABLE_ENTITY: UNPROCESSABLE_ENTITY,
    HTTP_OK: HTTP_OK,
    INTERNAL_ERROR : INTERNAL_ERROR
};